name: Run Python Script Every 2 Hours

on:
  schedule:
    - cron: '0 */2 * * *'  # 每 2 小時執行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 檢出程式碼
        with:
          persist-credentials: true  # 保持身份驗證以推送變更

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # 設定 Python 版本

      - name: Install dependencies
        run: pip install pandas numpy requests matplotlib bs4  # 直接安裝 pandas

      - name: Set execution permissions
        run: chmod +x main.py trend_image.py  # 賦予腳本執行權限

      - name: Get player price
        run: python main.py  # 執行 Python 腳本

      - name: Create image
        run: python trend_image.py  # 執行 Python 腳本

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-update from GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Actions 內建權限推送變更
